# Generated by Django 4.2.1 on 2023-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='uid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
