# Generated by Django 4.2.1 on 2023-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0007_alter_load_options_alter_truck_options_load_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadtruck',
            name='distance',
            field=models.FloatField(),
        ),
    ]
