# Generated by Django 4.2.1 on 2023-05-25 09:27

from django.db import migrations, models
import django.db.models.deletion
import loads.utils


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0008_alter_loadtruck_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadtruck',
            options={'ordering': ('distance',)},
        ),
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.ForeignKey(default=loads.utils.set_location, on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='loads.location'),
        ),
    ]
