# Generated by Django 4.2.1 on 2023-05-25 10:20

from django.db import migrations, models
import loads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0009_alter_loadtruck_options_alter_truck_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='uid',
            field=models.CharField(max_length=16, unique=True, validators=[loads.validators.validate_truck_uid]),
        ),
    ]
