# Generated by Django 4.2.1 on 2023-05-23 16:46

import django.core.validators
from django.db import migrations, models
import loads.utils


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_alter_location_zip_alter_track_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('capacity', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('location', models.ForeignKey(default=loads.utils.set_location, on_delete=loads.utils.set_location, related_name='truck', to='loads.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
