# Generated by Django 4.2.1 on 2023-05-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0003_truck_delete_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='near_trucks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='load',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='loads.location'),
        ),
        migrations.AlterField(
            model_name='load',
            name='pick_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='loads.location'),
        ),
    ]
