# Generated by Django 4.2.1 on 2023-05-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_load_near_trucks_alter_load_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='loads.load')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='loads.truck')),
            ],
        ),
    ]
