# Generated by Django 4.2.1 on 2023-05-24 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import loads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0006_remove_load_near_trucks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='load',
            name='truck',
            field=models.ManyToManyField(related_name='load', through='loads.LoadTruck', to='loads.truck'),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loadtruck',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loadtruck',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='loads.load'),
        ),
        migrations.AlterField(
            model_name='loadtruck',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='loads.truck'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=128, unique=True, validators=[loads.validators.validate_zip_code]),
        ),
        migrations.AddConstraint(
            model_name='loadtruck',
            constraint=models.UniqueConstraint(fields=('load', 'truck'), name='unique_load_truck'),
        ),
    ]
